#! /data/data/com.termux/files/usr/bin/bash

echo "=====================================" |lolcat

figlet -f smscript TERMUX |lolcat

echo "=====================================" |lolcat

PS1='\[\e[31m\]┌─[\[\e[37m\]\T\[\e[31m\]]─────\e[1;36m[TERMUX]\e[0;31m───[\#]\n|\n\e[0;31m└─[\[\e[31m\]\e[0;35m\W\[\e[31m\]]────►\e[1;32m'
